App_Login/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/',views.sign_up,name='signup'),
    path('signin/',views.sign_in,name='signin'),
    path('signout/',views.sign_out,name='signout'),
    path('profile/',views.user_profile,name='profile'),
    path('change-profile/',views.change_profile,name='change_profile'),
    path('password/',views.change_password,name='change_password'),
    path('add-picture/',views.add_pro_pic,name='add_pro_pic'),
    path('change-picture/',views.change_pro_pic,name='change_pro_pic'),
]

Blog/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from . import views
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('App_Login.urls')),
    path('blog/',include('App_Blog.urls')),
    path('',views.Index,name='index'),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
     user = models.OneToOneField(User, related_name='user_profile',on_delete=models.CASCADE)
     profile_pic = models.ImageField(upload_to ='profile_pics' )

App_Login/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from .models import UserProfile
from django.forms import fields

class SignUpForm(UserCreationForm):
     email = forms.EmailField(label='Email Address',required=True)

     class Meta:
          model = User
          fields = ('username','email','password1','password2')

class UserProfileChange(UserChangeForm):
     class Meta:
          model = User
          fields = ('username','email','first_name','last_name','password')

class ProfilePic(forms.ModelForm):
     class Meta:
          model = UserProfile
          fields = ['profile_pic',]
     

App_Login/views.py
from django.shortcuts import redirect, render, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,PasswordChangeForm
from django.contrib.auth import authenticate,login, logout
from django.contrib.auth.decorators import login_required

import App_Login
from .forms import SignUpForm,UserProfileChange,ProfilePic

# Create your views here.
def sign_up(request):

     form = SignUpForm()

     registerd = False
     if request.method == 'POST':
          form = SignUpForm(data=request.POST)

          if form.is_valid():
               form.save()
               registerd = True
     dict = {'form': form,'registerd':registerd}

     return render(request,'App_Login/signup.html',context=dict)

def sign_in(request):
     form = AuthenticationForm()

     if request.method == "POST":
          form = AuthenticationForm(data = request.POST )

          if form.is_valid():
               username = form.cleaned_data.get('username')
               password = form.cleaned_data.get('password')

               user = authenticate(username= username,password = password)

               if user is not None:
                    login(request,user)
                    return HttpResponseRedirect(reverse('index'))

     return render(request,'App_Login/signin.html',context={'form':form})

@login_required
def sign_out(request):
     logout(request)
     return HttpResponseRedirect(reverse('index'))


@login_required
def user_profile(request):
     return render(request,'App_Login/profile.html',context={})


@login_required
def change_profile(request):
     current_user = request.user

     form = UserProfileChange(instance=current_user)
     if request.method == "POST":
          form = UserProfileChange(request.POST, instance = current_user)

          if form.is_valid():
               form.save()
               form = UserProfileChange(instance=current_user)

     return render(request,'App_Login/change_profile.html',context={'form':form})

@login_required
def change_password(request):
     current_user = request.user
     form = PasswordChangeForm(current_user)

     if request.method == "POST":
          form = PasswordChangeForm(current_user,data = request.POST)
          if form.is_valid():
               form.save()

     return render(request,'App_Login/change_password.html',context={'form':form})

@login_required
def add_pro_pic(request):
     form = ProfilePic()

     if request.method == "POST":

          form = ProfilePic(request.POST,request.FILES)

          if form.is_valid():
               user_obj = form.save(commit=False)

               user_obj.user = request.user
               user_obj.save() #commit true default
               return HttpResponseRedirect(reverse('App_Login:profile'))

     return render(request,'App_Login/add_pro_pic.html',context={'form': form})

@login_required
def change_pro_pic(request):
     form = ProfilePic(instance=request.user.user_profile)
     if request.method == "POST":
          form = ProfilePic(request.POST,request.FILES,instance=request.user.user_profile)
          if form.is_valid():
               form.save()
               return HttpResponseRedirect(reverse('App_Login:profile'))

     return render(request,'App_Login/add_pro_pic.html',context={'form': form})

templates/App_Login/add_pro_pic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{%block title%} Change Profile Picture {% endblock %}

{% block body_block%}
<div class="container" style="padding-top: 20px;">

     <h2>Add Your Profile Picture</h2>
     <form method="POST" enctype="multipart/form-data">
          {{form | crispy}}
          {% csrf_token %}
          <br>
          <button type="submit" class="btn btn-success btn-sm">Change Picture</button>
     </form>
    
</div>
{% endblock %}

templates/App_Login/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{%block title%} Change Password {% endblock %}

{% block body_block%}
<div class="container" style="padding-top: 20px;">

     <h2>Change Your Old Password</h2>
     <form method="POST">
          {{form | crispy}}
          {% csrf_token %}
          <br>
          <button type="submit" class="btn btn-danger btn-sm">Change Password</button>
     </form>
     <br>
</div>
{% endblock %}

templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{%block title%} Change Profile {% endblock %}

{% block body_block%}
<div class="container" style="padding-top: 20px;">

     <h2>User Profile</h2>
     <form method="POST">
          {{form | crispy}}
          {% csrf_token %}
          <br>
          <button type="submit" class="btn btn-danger btn-sm">Submit Change</button>
     </form>
{% endblock %}

templates/App_Login/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Profile {% endblock %}


{%block body_block%}
<div class="container">
     <h2>Your Profile</h2>
     {% if user.user_profile %}
          <img src='/media/{{user.user_profile.profile_pic}}' class="rounded-circle" height="100px" width="100px"> 
          <br>
          <br>
          <a href="{% url 'App_Login:change_pro_pic'%}" class="btn btn-info btn-sm">Change Picture</a>
     {% else %}
          <img src='/media/profile_pics/avatar.png' class="rounded-circle" height="100px" width="100px">
          <br>
          <br>
          <a href="{% url 'App_Login:add_pro_pic'%}" class="btn btn-info btn-sm">Add Picture</a>
     {% endif %}
     
     <br>
     <br>

     <p>Username: {{user.username}}</p>
     <p>Email: {{user.email}}</p>
     <p>Name: {{user.first_name}} {{user.last_name}}</p>

     <br>
     <a href="{%url 'App_Login:change_profile'%}" class="btn btn-warning btn-sm">Change Profile Info</a>
</div>

{%endblock%}

templates/App_Login/signin.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{%block title%} Account Signin {% endblock %}

{% block css %}
<style>
@import url("https://fonts.googleapis.com/css?family=Roboto:300,400");

.form-area .form-content,
.form-area .form-input {
  box-sizing: border-box;
}

.form-area .form-content {
  padding: 40px 30px;
  background: rgba(103, 58, 183, 0.7);
  box-shadow: 0 0 40px 0 #e1e1e1;
}

.form-area .form-content h2 {
  color: #fff;
}
.form-area .form-content p {
  color: #fff;
}
.form-area .form-content ul {

  text-align: center;
}

.form-area .form-content ul li {
  display: inline-block;
  margin-right: 10px;
}
.form-area .form-content ul li i{
  text-align: left;
  margin-right: 10px;
}


.form-area .form-content .box {
  display: block;
  padding: 6px 10px;
  background: #3b579d;
  color: #fff;
  font-size: 10px;
  text-transform: capitalize;
  border-radius: 4px;
  border: 1px solid #3b579d;
  -webkit-transition: all 0.5s;
  -o-transition: all 0.5s;
  transition: all 0.5s;
  margin-bottom: 5px;
}

.form-area .form-content .box:hover,
.form-area .form-content .box:focus {
  background: transparent;
}


.form-area .form-input {
  background: #fff;
  padding: 40px 30px;
}

.form-area .form-input h2 {
  margin-bottom: 20px;
  color: #07315b;
}

.form-area .form-input input {
  position: relative;
  height: 60px;
  padding: 20px 0;
}
.form-area .form-input textarea {
  height: 120px;
  padding: 20px 0;
}

.form-area .form-input input,
.form-area .form-input textarea {
  text-transform: capitalize;
  width: 100%;
  box-sizing: border-box;
  outline: none;
  border: none;
  border-bottom: 2px solid #e1e1e1;
  color: #07315b;
}
.form-area .form-input form .form-group {
  position: relative;
}
.form-area .form-input form .form-group label {
  position: absolute;
  text-transform: capitalize;
  top: 20px;
  left: 0;
  pointer-events: none;
  font-size: 14px;
  color: #595959;
  margin-bottom: 0;
  transition: all 0.6s;
}
.form-area .form-input input:focus ~ label,
.form-area .form-input textarea:focus ~ label,
.form-area .form-input input:valid ~ label,
.form-area .form-input textarea:valid ~ label {
  top: -5px;
  opacity: 0;
  left: 0;
  color: rgba(103, 58, 183);
  font-size: 12px;
  color: #07315b;
  font-weight: bold;
}
.form-area .form-input input:focus,
.form-area .form-input textarea:focus,
.form-area .form-input input:valid,
.form-area .form-input textarea:valid {
  border-bottom: 2px solid rgba(103, 58, 183);
}
.form-area .form-text {
  margin-top: 30px;
}
.form-area .form-text span a {
  color: rgba(103, 58, 183);
}
.form-area .myform-button {
  margin-top: 30px;
}
.form-area .myform-button .myform-btn {
  width: 100%;
  height: 50px;
  font-size: 17px;
  background: rgba(103, 58, 183);
  border: none;
  border-radius: 50px;
  color: #fff;
  cursor: pointer;
  -webkit-transition: all 0.5s;
  -o-transition: all 0.5s;
  transition: all 0.5s;
}
.form-area .myform-button .myform-btn:hover {
  background: #07315b;
}

</style>

{% endblock %}

{% block body_block%}
<div class="container sty">
     
        <div class="row">
          <div class="col-lg-8" style="box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;">
            <div class=" form-area login-form row">
              <div class=" form-input col-md-6">
                <h2>Signin Form</h2>
                    <form method="POST">
                      <div class="form-group">
                        {{form.username}}
                        <label>User Name</label>
                      </div>
                      <div class="form-group">
                        {{form.password}}
                        <label>password</label>
                      </div>
                      <div class="myform-button">
                        <button class="myform-btn">Login</button>
                      </div>
                      {% csrf_token %}
                    </form>

              </div>
              <div class="form-content col-md-6">
                <h2>Signin With</h2>
                    <ul style="margin-top: 20px; display: flex; flex-direction: column;">
                      <li><a href="#" class="box"><i class="fa-brands fa-google"></i>Google</a></li>
                      <li><a href="#" class="box"><i class="fa-brands fa-facebook"></i>Facebook</a></li>
                      <li><a href="#" class="box"><i class="fa-brands fa-github"></i>Github</a></li>
                      <li><a href="#" class="box"><i class="fa-brands fa-linkedin"></i>Linkedin</a></li>
                    </ul>
                    <p style="text-align: center;   margin-top: 20px;">Don't have an account? <a style="color: rgb(202, 233, 241);" href="{% url 'App_Login:signup' %}">Signup</a></p>

              </div>
            </div>
          </div>
        </div>

</div>
{% endblock %}

templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{%block title%} Account Signup {% endblock %}

{% block body_block%}
<div class="container" style="padding-top: 20px;">
     {% if registerd %}
     <div class="alert alert-success">
          Account Created Successfully! <a href="{% url 'App_Login:signin' %}">Login Here</a>
     </div>
     {% else %}
     <h2>Create New Account</h2>
     <form method="POST">
          {{form | crispy}}
          {% csrf_token %}
          <button type="submit" class="btn btn-success btn-sm">Signup</button>
     </form>
     <br>
     <p style="text-align: center;">Already have an account? <a href="{% url 'App_Login:signin' %}">Signin</a></p>
     {% endif %}
</div>

{% endblock %}