App_Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.edit import UpdateView
from . import views
app_name = 'App_Blog'

urlpatterns = [
    path('',views.BlogList.as_view(),name='blog_list'),
    path('write/',views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug>',views.blog_details, name='blog_details'),
    path('liked/<pk>/',views.liked, name='liked_post'),
    path('unliked/<pk>/',views.unliked, name='unliked_post'),
    path('my-blogs/',views.MyBlogs.as_view(),name='my_blogs'),
    path('edit/<pk>',views.UpdateBlog.as_view(),name='edit_blog'),
    path('delete/<pk>',views.delete_blog,name='delete_blog'),
]

App_Login/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/',views.sign_up,name='signup'),
    path('signin/',views.sign_in,name='signin'),
    path('signout/',views.sign_out,name='signout'),
    path('profile/',views.user_profile,name='profile'),
    path('change-profile/',views.change_profile,name='change_profile'),
    path('password/',views.change_password,name='change_password'),
    path('add-picture/',views.add_pro_pic,name='add_pro_pic'),
    path('change-picture/',views.change_pro_pic,name='change_pro_pic'),
]

Blog/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from . import views
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('App_Login.urls')),
    path('blog/',include('App_Blog.urls')),
    path('',views.Index,name='index'),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
               
    {% endblock %}
  </title>
  {% block css%}

    

  {% endblock %}
  <link rel="stylesheet" href="{% static 'css/style.css'%}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
     <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
          <a class="navbar-brand" href="{% url 'index' %}"><u style="font-size: 30px;"> <code>&#60;code&#62;</code><span style="font-size: 25px;">Tracking</span></u></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'App_Blog:blog_list' %}">Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Course</a>
              </li>
            </ul>

            <div class="nav-right">

              {% if user.is_authenticated %}
              <a href="{% url 'App_Blog:create_blog'%}" class="btn btn-success btn-sm" style="margin-right: 10px;">Write Blog</a>
                <div class="nav-item dropdown btn btn-light btn-sm">
                  <a href="#" id='navbardrop' class="nav-link dropdown-toggle" data-toggle="dropdown">
                    <img src='/media/{{user.user_profile.profile_pic}}' class="rounded-circle" height="20px" width="20px">
                    {{user.username}}
                  </a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Profile</a>
                    <a href="{% url 'App_Blog:my_blogs'%}" class="dropdown-item">My Blogs</a>
                    <a class="dropdown-item" href="{% url 'App_Login:signout' %}">Signout</a>
                  </div>
                </div>
                
              {% else %}
                <a href="{% url 'App_Login:signin' %}" class="btn btn-primary btn-sm">Signin</a>
                <a href="{% url 'App_Login:signup' %}" class="btn btn-success btn-sm">Signup</a>
              {% endif%}
            </div>
          </div>
        </nav>
        {%block body_block %}
        
        {%endblock%}

        <div id="footer">
          <div class="row">
            <div class="col-md-4">
              <h5>BLOG CATEGORY</h5>
              <div class="smart-ul"></div>
              <ul id="foot-ul" style="list-style-type:none;">
                <li><a href="#">Python</a></li>
                <li><a href="#">Javascript</a></li>
                <li><a href="#">MySQL</a></li>
                <li><a href="#">Bootstrap</a></li>
                <li><a href="#">CSS</a></li>
                <li><a href="#">HTML</a></li>
                <li><a href="#">C++</a></li>
                <li><a href="#">C</a></li>
              </ul>
  
            </div>
            <div class="col-md-4">
              <h5>ABOUT</h5>
              <div class="smart-ul"></div>
              <p>CodeTracking is programming blog where you can code, learn and write about programming. We share our knowledge about new web and application technology trends. Here you can learn so many things and you can follow our courses and examples.   </p>
            </div>
            <div class="col-md-4">
              <h5>CONSULTANCY</h5>
              <div class="smart-ul"></div>
              <p>systemstack.digital</p>
              <h5>CONTACT</h5>
              <div class="smart-ul"></div>
              <P>send@codetrack.com</P>
            </div>
          </div>
          <p id="foot-p"> © 2021 CodeTracking.com All Rights Reserved.</p>
        </div>
        
</body>
</html>

templates/home.html
{% extends 'base.html'%}
{% load static %}

{% load custom_filters %}

{% block title%} CodeTracking | Home {% endblock%}


{%block body_block%}
<div class="theme">
     <div id="th-body">
          <h1>Code, Write, Learn</h1>
          <p>Coding can be difficult, when you are alone.</p>
          {% if user.is_authenticated%}
               <a href="{% url 'App_Blog:create_blog'%}" class="btn btn-light">Start Writing</a>
          {% else %}
               <a href="{% url 'App_Login:signin'%}" class="btn btn-light">Start Writing</a>
          {% endif%}

     </div>
</div>
<div class="container">
     <div class="row" style="margin-top: 20px;">
          <div  class="col-md-4">
               <div id="tags">
                    <a href="#" class="btn btn-primary btn-sm">Python</a>
                    <a href="#" class="btn btn-primary btn-sm">Javascript</a>
                    <a href="#" class="btn btn-primary btn-sm">Django</a>
                    <a href="#" class="btn btn-primary btn-sm">NodeJS</a>
                    <a href="#" class="btn btn-primary btn-sm">React</a>
                    <a href="#" class="btn btn-primary btn-sm">jQuery</a>
                    <a href="#" class="btn btn-primary btn-sm">Bootstrap</a>
                    <a href="#" class="btn btn-primary btn-sm">HTML</a>
                    <a href="#" class="btn btn-primary btn-sm">CSS</a>
                    <a href="#" class="btn btn-primary btn-sm">MySQL</a>
                    <a href="#" class="btn btn-primary btn-sm">PostgreSQL</a>
                    <a href="#" class="btn btn-primary btn-sm">C++</a>
                    <a href="#" class="btn btn-primary btn-sm">C</a>
                    

               </div>
               <div id="build-app">
                    <img src="{% static 'images/build-app.jpg' %}" alt="cat-image" width="100%" >
                    <a href="#" class="btn btn-success btn-lg">Build Your Web App Now</a>
               </div>
               
     
          </div>
          <div class="col-md-8">
               <h3>RECENT BLOGS</h3>
               <div class="smart-ul"></div>
               
               {% for blog in blogs %}
                    {% if forloop.counter <= 5 %}
                    <div id="home-blog">
                         <h3 style="font-family:Verdana, Geneva, Tahoma, sans-serif;">{{blog.blog_title }}</h3>
                         <div class="bd-1">
                              <h6><i>{{blog.publish_date}}</i></h6>
                              <h6 style="margin-left: 5%;">Author: <a href="#">{{ blog.author}}</a></h6>
                         </div>

                         <div class="row">
                              <div class="col-sm-4">
                                   <img style="margin-top: 20px;" src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%" height="120px">
                              </div>
                              <div class="col-sm-8">
                                   <p>
                                        {{blog.blog_content|safe|slice:250}}

                                   </p>
                                   <div class="bd-2">
                                        <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}" class="btn btn-info btn-sm">Read More</a>
                                        <h6 style="margin-left: 15px; font-size: 20px;"><i class="fas fa-thumbs-up"></i>{{blog.liked_blog.count}} <i style="margin-left: 10px;"class="fas fa-comments"></i>  {{blog.blog_comment.count}}</h6>
                                   </div>
                                   

                              </div>
                         </div>
                    </div>
                    {% endif %}
               {% endfor %}
               <a class="btn btn-light btn-sm" style="position: relative; left: 40%; margin: 5% 0;" href="{% url 'App_Blog:blog_list'%}">SEE MORE</a>
          </div>
     </div>
</div>

{% endblock %}