App_Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.edit import UpdateView
from . import views
app_name = 'App_Blog'

urlpatterns = [
    path('',views.BlogList.as_view(),name='blog_list'),
    path('write/',views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug>',views.blog_details, name='blog_details'),
    path('liked/<pk>/',views.liked, name='liked_post'),
    path('unliked/<pk>/',views.unliked, name='unliked_post'),
    path('my-blogs/',views.MyBlogs.as_view(),name='my_blogs'),
    path('edit/<pk>',views.UpdateBlog.as_view(),name='edit_blog'),
    path('delete/<pk>',views.delete_blog,name='delete_blog'),
]

Blog/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from . import views
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('App_Login.urls')),
    path('blog/',include('App_Blog.urls')),
    path('',views.Index,name='index'),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


# Create your models here.

class Category(models.Model):
     name = models.CharField(max_length=264, verbose_name="Category Name")

     class Meta:
          verbose_name_plural = "Categories"

     def __str__(self):
          return self.name




class Blog(models.Model):
     author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='post_author')
     category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name='post_category')
     blog_title = models.CharField(max_length=264,verbose_name="Put a Title")
     slug = models.SlugField(max_length=264,unique=True)
     blog_content = RichTextField(blank=True,null=True)
     #blog_content = models.TextField(verbose_name="Write your article here...")
     blog_image = models.ImageField(upload_to='blog_images', verbose_name="Image")
     publish_date = models.DateTimeField(auto_now_add=True)
     update_date = models.DateTimeField(auto_now=True)


     #A way to show blog list in acending and decending order using the - sign
     #we can also make it from views file
     class Meta:
          ordering = ['-publish_date']

     def __str__(self):
         return self.blog_title

class Comment(models.Model):
     blog = models.ForeignKey(Blog,on_delete=models.CASCADE,related_name='blog_comment')
     user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='user_comment')
     comment = RichTextField(blank=True,null=True)
     comment_date = models.DateTimeField(auto_now_add=True)

     def __str__(self):
          return self.comment

class Likes(models.Model):
     blog = models.ForeignKey(Blog,on_delete=models.CASCADE,related_name='liked_blog')
     user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='liked_user')

     def __str__(self):

          return str(self.user)+ " liked " + str(self.blog)

App_Blog/forms.py
from django import forms
from django.forms import fields
from .models import Blog, Comment

class CommentForm(forms.ModelForm):
     class Meta:
          model = Comment
          fields = ('comment',) 

App_Blog/views.py
import imp
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView, DetailView, View, TemplateView, ListView
from .models import Blog, Comment, Likes
import uuid
from .forms import CommentForm

from django.contrib.auth.decorators import login_required #Used in function based views
from django.contrib.auth.mixins import LoginRequiredMixin #Used in class based views


# Create your views here.
class MyBlogs(LoginRequiredMixin,TemplateView):
     template_name = 'App_Blog/my_blogs.html'


class CreateBlog(LoginRequiredMixin, CreateView):
     model = Blog
     template_name = 'App_Blog/create_blog.html'
     fields = ('category','blog_title','blog_content','blog_image',)

     def form_valid(self,form):
          blog_obj = form.save(commit=False)
          blog_obj.author = self.request.user 
          title = blog_obj.blog_title
          #blog_obj.blog_image = form.cleaned_data['image']
          blog_obj.slug = title.replace(" ","-") + "-" + str(uuid.uuid4())
          blog_obj.save()

          return HttpResponseRedirect(reverse_lazy('index'))

class BlogList(ListView):
     context_object_name = 'blogs'
     model = Blog
     template_name = 'App_Blog/blog_list.html'
     #queryset = Blog.objects.order_by('-publish_date') #we also can make it from model

#@login_required
def blog_details(request, slug):
     blog = Blog.objects.get(slug=slug)
     
     if request.user.is_authenticated:
          comment_form = CommentForm()
          already_liked = Likes.objects.filter(blog = blog, user = request.user)
          if already_liked:
               liked = True
          else:
               liked = False

          if request.method == 'POST':
               comment_form = CommentForm(request.POST)
               if comment_form.is_valid():
                    comment = comment_form.save(commit=False)
                    comment.user = request.user
                    comment.blog = blog
                    comment.save()

                    return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':slug}))

          return render(request,'App_Blog/blog_details.html',context={'blog':blog, 'comment_form':comment_form, 'liked':liked})
     else:
          return render(request,'App_Blog/blog_details.html',context={'blog':blog})


@login_required
def liked(request,pk):
     blog = Blog.objects.get(pk=pk)
     user = request.user
     already_liked = Likes.objects.filter(blog=blog,user=user)

     if not already_liked:
          like_post = Likes(blog=blog,user=user)
          like_post.save()

          return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':blog.slug}))


@login_required
def unliked(request,pk):
     blog = Blog.objects.get(pk=pk)
     user = request.user
     already_liked = Likes.objects.filter(blog=blog,user=user)
     already_liked.delete()

     return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':blog.slug}))

class UpdateBlog(LoginRequiredMixin, UpdateView):

     model = Blog

     fields = ('blog_title','blog_content','blog_image',)
     template_name = 'App_Blog/edit_blog.html'

     def get_success_url(self,**kwargs):
          return reverse_lazy('App_Blog:blog_details', kwargs={'slug':self.object.slug})


def delete_blog(request,pk):
     user = request.user
     post = Blog.objects.get(pk=pk,author=user)

     if post:
          post.delete()
     else:
          print('No Post')

     return HttpResponseRedirect(reverse('App_Blog:my_blogs'))

templates/App_Blog/blog_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%} {{blog.blog_title}} {% endblock %}


{% block body_block %}
<div class="container d-flex flex-direction-column">
     <div class="row">
          <div class="col-6">
               <h2>{{blog.blog_title}}</h2>
               <h6><i class="fa-solid fa-feather-pointed"></i> {{blog.author}}</h6>
               <h6><i class="fa-solid fa-tag"></i> {{blog.category}}</h6>
               <i><h6><i class="fa-regular fa-calendar-check"></i> {{blog.publish_date}}</h6></i>

               <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} Comments</h6>
               
          </div>
          <div class="col-6">
               <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" width="100%">
          </div>
          <p>
               {{blog.blog_content|safe}}
          </p>
     </div>
     <hr>
     {% if user.is_authenticated %}
          {% if not liked%}
          <a href="{% url 'App_Blog:liked_post' pk=blog.pk%}"><i class="fa-regular fa-heart"></i></a>
          {% else %}
          <a href="{% url 'App_Blog:unliked_post' pk=blog.pk%}"><i style=" color: rgb(228, 90, 90);" class="fa-solid fa-heart"></i></a>
          {% endif %} 
          <hr>
          <div class="row">
               <div class="col-md-6">
                    <h3>Comments:</h3>
                    {% for comment in blog.blog_comment.all%}
                    <p><a href="#">@{{comment.user}}</a> > {{comment.comment}}</p>
                    <h6>{{comment.comment_date}}</h6>
                    <hr>
                    {% endfor %}
               </div>
               <div class="col-md-6">
                    <form method="POST">
                         {{comment_form | crispy}}
                         {% csrf_token %}
                         <button type="submit" class="btn btn-primary btn-sm">Comment</buuton>
                    </form>
               </div>
          </div>
     {% else %}
     <div class="row">
          <div class="col-md-6">
               <h3>Comments:</h3>
               {% for comment in blog.blog_comment.all%}
               <p><a href="#">@{{comment.user}}</a> > {{comment.comment}}</p>
               <h6>{{comment.comment_date}}</h6>
               <hr>
               {% endfor %}
          </div>
          <div class="col-md-6">
               <p>You are not allowed to like and comment in a post untill you are not a rgisterd user.</p>
               
          </div>
     </div>
          
     {% endif %}
</div>
<br>
<br>

{% endblock %}

templates/App_Blog/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title %} Blog {% endblock %}

{% block body_block %}
<div class="container">
     <h3 style="text-align: center;">ALL BLOGS</h3>
     <div class="smart-ul"></div>
     <div class="row">
     {% for blog in blogs %}
     <div class="col-md-4" style="margin-top: 10px;">
          <a  style="text-decoration: none;"href="{% url 'App_Blog:blog_details' slug=blog.slug %}">
               <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%" height="60%">
               <i style="font-size: 10px;">{{blog.publish_date}}</i>
               <h3 style="font-family:Arial, Helvetica, sans-serif; color: black; font-size: 18px; font-weight:bold; text-decoration: none;">{{blog.blog_title }}</h3>
          </a>
     </div>
     {% endfor %}
     </div>
</div>
{%endblock%}

templates/App_Blog/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%} Create Blog  {% endblock %}

{% block body_block %}
<div class="container">
     <h2> Write Your Blog</h2>
     <form method="POST" enctype="multipart/form-data">
          {{form.media}}
          {{form | crispy}}
          {% csrf_token %}
          <br><br>
          <button type="submit" class="btn btn-success btn-sm">Post Blog</button>
     </form>
</div>
{% endblock %}

templates/App_Blog/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags%}
{% block title%} blog.blog_title {% endblock %}


{% block body_block %}
<div class="container">
     {% if blog.author ==  user %}
     <form method="POST" enctype="multipart/form-data">
          {{form.media}}
          {{form | crispy}}
          {% csrf_token%}
          <button type="submit" class="btn btn-warning btn-sm">Upadate</button>
     </form>
     {% else%}
     <p>You are not allowed to view this page. Error: 404</p>
     {% endif %}

</div>

{% endblock %}

templates/App_Blog/my_blogs.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title%} {{ user }} {% endblock %}


{% block body_block %}

<div class="container" style="margin: 20px 0">
     {% for blog in user.post_author.all %}
     <div id="home-blog">
          <h3>{{blog.blog_title}}</h3>
          <h6>Published:{{blog.publish_date}} | Updated On: {{blog.update_date}} </h6> 
          <i class="fas fa-thumbs-up"></i>{{blog.liked_blog.count}} | <i class="fas fa-comments"></i>  {{blog.blog_comment.count}}
          <div class="row">
               <div class="col-sm-4">
                    <img src="/media/{{blog.blog_image}}" alt="" width="100%">
               </div>
               <div class="col-sm-8">
                    {{blog.blog_content|safe|slice:250}}
                    <a class="btn btn-info btn-sm" href="{% url 'App_Blog:blog_details' slug=blog.slug %}">See More</a> <a class="btn btn-sm btn-warning" href="{% url 'App_Blog:edit_blog' pk=blog.pk %}">Edit Blog</a> <a class="btn btn-sm btn-warning" href="{% url 'App_Blog:delete_blog' pk=blog.pk %}">Delete Blog</a>
               </div>
          </div>
     </div>


     {%endfor%}
</div>
{% endblock %}